### ISSUE TITLE
Model analysis Tensorflow requirement issue

### ISSUE THREAD

**Issue by akewan** [tensorflow/model-analysis#120]
The requirment for Tensorflow in model analysis at:
https://github.com/tensorflow/model-analysis/blob/67a4d9601b6e735307480c53a1227c691efc6d20/setup.py#L303
is incorrect. A coma is missing before "!=2.3.*" as it is at TFX install requirments:
https://github.com/tensorflow/tfx/blob/21e5af7f9543e108328c1a83b9132acda4875d93/tfx/dependencies.py#L88
This missing come reinstalls an already installed version of Tensorflow 2.4.0 and installs a 2.4.1 version of it

**Comment by arghyaganguly** [comment]
@akewan , thanks for reporting this bug.A PR has been raised to address it.Thanks.

**Comment by dhruvesh09** [comment]
This is been addressed in 
https://github.com/tensorflow/model-analysis/commit/19d49dc274c38201b6cb3ea9d6c7b9c5f006a244
