### ISSUE TITLE
Is line #96 of examples/chicago_taxi/model.py example a bug ?

### ISSUE THREAD

**Issue by nilbody** [tensorflow/model-analysis#14]
https://github.com/tensorflow/model-analysis/blob/2fb97d4d6bac1b800c340ca9a6f2393bd5169cf2/examples/chicago_taxi/trainer/model.py#L96

The tf.estimator.export.ServingInputReceiver has only a constructor with 2 parameters which are features and receiver_tensors.
But in line#96 ServingInputReceiver is created with 2 parameters : transformed_features and serving_input_receiver.features, no receiver_tensors.

**Comment by harshini-gadige** [comment]
@chuanyu  -  Is this fixed now ?

**Comment by chuanyu** [comment]
Yes, this has been fixed.
