### ISSUE TITLE
Move to numpy >=1.20 because <1.20 is difficult to build on Apple Silicon

### ISSUE THREAD

**Issue by sradc** [tensorflow/model-analysis#169]
https://github.com/tensorflow/model-analysis/blob/b4f2e9fe2733a8ee4d6a129facf23efdc4b162ba/setup.py#L297

Numpy `>=1.20` is easy to install on Apple silicon, because it's precompiled, but `1.19` fails unless openblas is set up on the system (which it will not be for most users). (See [this NumPy](https://github.com/numpy/numpy/issues/17807) issue.)

See also this issue in scipy where they moved away from 1.19 because it fails to build on Apple Silicon. https://github.com/scipy/oldest-supported-numpy/issues/19

**Comment by gaikwadrahul8** [comment]
Hi, @sradc 

Apologies for the delay and as we mentioned in TFMA setup file `numpy>=1.16,<2` is not specific to particular OS so it seems like `numpy==1.19` needs `openblas` set up to install `numpy==1.19` so as you mentioned `numpy==1.20` working fine so I would suggest you to go with `numpy>=1.20` because as you confirmed it's working fine and as of now we haven't noticed issues which is related to `numpy==1.19` w.r.t Apple Silicon

Please let me know if I'm missing something here or you need any further assistance ?

Thank you!

**Comment by sradc** [comment]
Hey @gaikwadrahul8,

Thanks for the response. (I'm a bit confused about what's going on.) Does TFMA support Apple Silicon? I'm trying to install it alongside [tensorflow-metal](https://developer.apple.com/metal/tensorflow-plugin/). 

- When I run `pip install tensorflow-model-analysis`, it's been trying to install `numpy=1.19.*`, even though `numpy=1.24.*` is installed. (I checked, and it is trying to install `tensorflow-model-analysis==0.43.0`). 
- When I run `pip install 'tensorflow-model-analysis==0.43.0'`, it doesn't try to downgrade numpy, but the install fails with `tfx-bsl`, saying `ERROR: Could not find a version that satisfies the requirement tfx-bsl (from versions: none)`.

I'm thinking this could be user error on my part, so will keep trying things, but letting you know on the off chance you have any information that might help.

**Comment by gaikwadrahul8** [comment]
Hi, @sradc 

You can install Tensorflow with the help of `tensorflow-metal plugin` and use it but at the moment it seems like we do not support TFX and supported libraries like TFMA, TFDV and TFT for Apple Silicon(M1) you can check [similar issue ](https://github.com/tensorflow/data-validation/issues/205)and same discussion going on our [Tensorlflow Forum ](https://discuss.tensorflow.org/t/i-want-to-use-the-tfx-1-6-1-on-mac-m1-max/8110), In the meantime, some users have reported success with Rosetta. Other options include using a VM. We understand that neither of those is ideal.

If I'm missing something here, please let me know ? Thank you!

**Comment by sradc** [comment]
Thanks @gaikwadrahul8, appreciate the info. 👍
