### ISSUE TITLE
Error while using tfdv.generate_statistics_from_csv('path_to_csv_file')

### ISSUE THREAD

**Issue by akki3d76** [tensorflow/model-analysis#28]
I got a error while using this-

train_stats = tfdv.generate_statistics_from_csv('data_1.csv')
(the path to data is correct)

**Error-** ValueError: No line was found. [while running 'DecodeData/ParseCSVRecords']

**Comment by harshini-gadige** [comment]
@akki3d76  - Hi, there is a seperate Github repository for Tensorflow data-validation. Request you to post the query in the tfdv repo. Please find the link to tfdv repo below.

[](https://github.com/tensorflow/data-validation/issues)
