### ISSUE TITLE
WriteTFRecord includes full path to output file

### ISSUE THREAD

**Issue by cyc** [tensorflow/model-analysis#47]
This is not a very significant bug, but it is a bit unexpected behavior. In [the code](https://github.com/tensorflow/model-analysis/blob/545106a1725e4203788b6a1469108c97954f8a7d/tensorflow_model_analysis/api/model_eval_lib.py#L315) output files are written via a `beam.io.WriteToTFRecord` PTransform, but the name is assigned as `'WriteTFRecord(%s)' % output_file`. The problem is that the `output_file` is generally an absolute path to some file, using `/` as a delimiter. In the Google Cloud Dataflow UI it seems like `/` in the step name is used to group together similar operations, so you end up with a deeply-nested graph structure where `WriteTFRecord(gs://path/to/file)` gets mapped to `'WriteTFRecord(gs:' > '' > 'path' > 'to' > 'file'`.

**Comment by mdreves** [comment]
The default writers now uses MetricsAndPlotsWriter which has a stage name of 'WriteMetricsAndPlots', so this is no longer an issue.
