### ISSUE TITLE
`static` folder missing when installing Jupyter notebook extensions

### ISSUE THREAD

**Issue by benjamintanweihao** [tensorflow/model-analysis#50]
### System information
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
-   **TensorFlow Model Analysis installed from (source or binary)**: binary
-   **TensorFlow Model Analysis version (use command below)**: 0.13.2
-   **Python version**: 2.7 / 3.5
-   **Jupyter Notebook version**:  5.7.8
-   **Exact command to reproduce**:

### Describe the problem

I'm following the instructions to install the TFMA Jupyter extension via Conda and I realized that at `jupyter nbextension install --py --symlink tensorflow_model_analysis`:

```
% jupyter nbextension install --py --symlink tensorflow_model_analysis
/home/benjamintan/miniconda3/lib/python3.7/site-packages/apache_beam/__init__.py:84: UserWarning: Running the Apache Beam SDK on Python 3 is not yet fully supported. You may encounter buggy behavior or missing features.
  'Running the Apache Beam SDK on Python 3 is not yet fully supported. '

Installing /home/benjamintan/miniconda3/lib/python3.7/site-packages/tensorflow_model_analysis/static -> tfma_widget_js
Symlinking: /usr/local/share/jupyter/nbextensions/tfma_widget_js -> /home/benjamintan/miniconda3/lib/python3.7/site-packages/tensorflow_model_analysis/static
- Validating: problems found:
   X  require: /usr/local/share/jupyter/nbextensions/tfma_widget_js/extension.js
  OK section: notebook
Full spec: {'section': 'notebook', 'src': 'static', 'dest': 'tfma_widget_js', 'require': 'tfma_widget_js/extension'}

    To initialize this nbextension in the browser every time the notebook (or other app) loads:

          jupyter nbextension enable tensorflow_model_analysis --py
```

What I've found is that the `/home/benjamintan/miniconda3/lib/python3.7/site-packages/tensorflow_model_analysis/static` doesn't exist. This causes the widgets not to load.

However, when I manually copy the files from Github to the aforementioned directory, the widgets then load.

I've tried to use `--system` and `--sys-prefix` without any success.

**Comment by pfyang** [comment]
Hi,

We currently do not support TFMA with conda. Could you please try using pip install with virtualenv?

Also, please use --sys-prefix when using virtualenv as suggested in the installation insrtuction:
  https://github.com/tensorflow/model-analysis#installation

Thanks!

**Comment by kwlzn** [comment]
we're hitting this issue too (outside of conda) at Twitter. it looks like the `static` folder is missing inside the pypi published bdist:

```
[omerta show]$ wget -q https://files.pythonhosted.org/packages/c5/5e/e56ccce03d780d49755148978693f74c3da12f08e0b903417f5c711e0c12/tensorflow_model_analysis-0.14.0-py3-none-any.whl
[omerta show]$ unzip -l tensorflow_model_analysis-0.14.0-py3-none-any.whl |grep static
[omerta show]$ 
```

it looks like there's probably some pre-setup.py execution step missing in the wheel build that needs to be handled to generate the static assets?

**Comment by kwlzn** [comment]
we're also seeing this issue at Twitter and have PR #55 out to resolve, if someone could take a look.

**Comment by arghyaganguly** [comment]
Closing this as there has been no update lately.Please fee free to reopen based on above comment trace.
