### ISSUE TITLE
Wrong batch size pass to predictor

### ISSUE THREAD

**Issue by zzhang2019** [tensorflow/model-analysis#53]
### System information
0.13.*

### Describe the problem

When predictor input with batch size, say 256, we need to specify batch size (by setting desired_batch_size) when calling run_model_analysis (as in PR: https://github.com/tensorflow/model-analysis/pull/48/), or ExtractEvaluateAndWriteResults,  the problem is that if my input has 300 examples, first batch will be 256 will runs ok, but the second batch will be with 44 example feeding to predictor which will crash predictor (since batch size does not match).

One easy fix is to ignore not mismatched size of batch by adding a filter here: 
https://github.com/tensorflow/model-analysis/blob/master/tensorflow_model_analysis/extractors/predict_extractor.py#L81
if (self._desired_batch_size and self._desired_batch_size != batch_size):
        print("Skip process for {} element since batch size does not match".format(batch_size))
        return

**Comment by mdreves** [comment]
Can you post a trace for the crash that you are seeing. The model should accept varying batch sizes and we certainly don't want to skip running predictions for some of the examples.

**Comment by zzhang2019** [comment]
In my case, the reason my model does not accept varying batch size is I that I explicitly set batch size for my eval_input_receiver_fn (I cannot leave it as None for tf graph parsing issue).

def eval_input_receiver_fn(self, batch_size):
        serialized_tf_example = tf.placeholder(
            dtype=tf.string, shape=[batch_size], name='input_example_tensor')
        # The key name MUST be 'examples'.
        receiver_tensors = {'examples': serialized_tf_example}
        raw_features = tf.parse_example(serialized_tf_example,
                                        self._feature_specs)
        return tfma.export.EvalInputReceiver(
            features=raw_features,
            receiver_tensors=receiver_tensors,
            labels=None)

**Comment by mdreves** [comment]
I think you either need to pad your examples, truncate them at the source, or fix the model_fn.

**Comment by zzhang2019** [comment]
That is a fare argument, if tmfa require batch size of eval_fn to be None.
But this will push the hard part to tfma user given adding a filter in tfma is so easy (tf dataset also support this kind of filter) :)

**Comment by rmothukuru** [comment]
@zzhang2019 ,
Closing the issue as the resolution has been provided. Feel free to Open a Feature Request if you feel some functionality needs to be added. Thanks!
