### ISSUE TITLE
v0.14.0 tag points to the 0.15.0 release commit

### ISSUE THREAD

**Issue by andrewsmartin** [tensorflow/model-analysis#58]
Hi, I was trying to look at the code for the 0.14.0 release, and I noticed that the `v0.14.0` tag actually points to https://github.com/tensorflow/model-analysis/commit/35ab9fc9f8f5e137baff07f208bf51120135884f. Is someone able to fix this?

**Comment by mdreves** [comment]
Try now, should be fixed.
