### ISSUE TITLE
Saw the demo at the conference,, but

### ISSUE THREAD

**Issue by dartdog** [tensorflow/model-analysis#6]
I was so hopeful after seeing the demo. When going to use the analysis was very disappointing to note the Py27 dependency,, which seems to be due to Beam,, why not just take the normal TF input flow?? eg among other things taking plain old csv files as input (ex Beam). I can think of no reason that Beam should be in the analysis package,, if it is needed/desired it should be structured as part of the TF IO package facilities. As it sits now, it seems like the package special purpose code that is not ready for users doing normal development on local machines for a variety of use cases.. Even Google Doc's generally advise working out flows, and this would include initial analysis, on local machines before deploying to cloud usage.. It seems pretty apparent that this is not getting much usage, if only due to the lack of SO activity (none) and the lack of GH issues,, just these two... Hopefully there is a plan to make this more usable as I feel it would be a huge help to model development.  We really need tools like this though!

**Comment by wjarek** [comment]
https://github.com/tensorflow/model-analysis/issues/8 tracks Python 3 support. Wrt usability - fair point, currently the project only contains the core library, more info on future plans here: https://youtu.be/vdG7uKQ2eKk.
