### ISSUE TITLE
TimeSeriesView and PlotViewer broken due to incorrect model_module in HTML export

### ISSUE THREAD

**Issue by dynamix** [tensorflow/model-analysis#67]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow Model Analysis)**: no
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Debian Buster
-   **TensorFlow Model Analysis installed from (source or binary)**: binary
-   **TensorFlow Model Analysis version (use command below)**: 0.22.1
-   **Python version**: 3.7.3
-   **Jupyter Notebook version**: 6.0.3

### Describe the problem

Module loading fails via unpck.com due to incorrect naming.  

https://github.com/tensorflow/model-analysis/blob/b5060f014ec76876327f9960433cf83aca4a9ddf/tensorflow_model_analysis/notebook/jupyter/tfma_widget/widget.py#L55 and https://github.com/tensorflow/model-analysis/blob/b5060f014ec76876327f9960433cf83aca4a9ddf/tensorflow_model_analysis/notebook/jupyter/tfma_widget/widget.py#L68 should be `tensorflow_model_analysis` instead of `tensorflow_model-analysis`

**Comment by mdreves** [comment]
Thanks for debugging. Submitted a fix, should be in next release.
