### ISSUE TITLE
Documentation needed?

### ISSUE THREAD

**Issue by tommywei110** [tensorflow/model-analysis#68]
Hi developers,

I don't know if this is the right place or channel to communicate this. But the [tfma website](https://www.tensorflow.org/tfx/model_analysis/api_docs/python/tfma) could use a bit more documentation.

Even though it is possible to dive in to the source code to find out the parameters and usage, the library usability can be greatly improved had there been a higher level explanation of the API available in tfma.

For example, the [tfma.genericvaluethreshold](https://www.tensorflow.org/tfx/model_analysis/api_docs/python/tfma/GenericValueThreshold) class conditions the pusher to only push models that are within the two bounds configured in this class.

I think this endeavor should slightly prioritized as it's the gateway for people to start using the library.

**Comment by mdreves** [comment]
Unfortunately our gendocs script doesn't currently pickup comments on protobufs. Looking into what we can do.
