### ISSUE TITLE
Binarize options in default_multi_class_classification_specs  is broken

### ISSUE THREAD

**Issue by JakeTheWise** [tensorflow/model-analysis#73]
# System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow Model Analysis)**: Yes
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu
-   **TensorFlow Model Analysis installed from (source or binary)**: binary (PyPI)
-   **TensorFlow Model Analysis version (use command below)**: 0.22.2
-   **Python version**: 3.6.8
-   **Jupyter Notebook version**: 6.0.3
-   **Exact command to reproduce**:
```python
tfma.metrics.default_multi_class_classification_specs(
    model_names=['model'],
    binarize=tfma.BinarizationOptions(class_ids={'values' : list(range(len(classes)))}),
    sparse=True
)
```
This gives the following error:
```
<ipython-input-17-1d79e900e9de> in <module>
      2     model_names=['model'],
      3     binarize=tfma.BinarizationOptions(class_ids={'values' : list(range(len(classes)))}),
----> 4     sparse=True
      5 )

/usr/local/lib/python3.6/site-packages/tensorflow_model_analysis/metrics/metric_specs.py in default_multi_class_classification_specs(model_names, output_names, binarize, aggregate, sparse)
    325       ])
    326     binarize = config.BinarizationOptions().CopyFrom(binarize)
--> 327     binarize.ClearField('top_k_list')  # pytype: disable=attribute-error
    328   multi_class_metrics = specs_from_metrics(
    329       metrics, model_names=model_names, output_names=output_names)

AttributeError: 'NoneType' object has no attribute 'ClearField'
```

**Comment by mdreves** [comment]
Thanks for raising the issue. Fixed at head.

**Comment by JakeTheWise** [comment]
@mdreves sorry but I don't think your commit quite fixes the issue. It still is overwriting the user's BinarizationOptions. Would you please consider looking at my PR? #74

**Comment by mdreves** [comment]
Sorry about that. I've committed a revised version of your fix. Thanks.
