### ISSUE TITLE
Support for Python 3

### ISSUE THREAD

**Issue by sebastianbk** [tensorflow/model-analysis#8]
What's the timeline for supporting Python 3?

TensorFlow only runs on Python 3.5 and 3.6 on Windows. So those of us who work on Windows machines have a harder time trying out TFMA.

**Comment by superbobry** [comment]
Apache Beam is almost Python 3 ready. I think this might be a good time to ensure the rest of model-analysis is as well. I'd be happy to give this a try once #12 is resolved.

**Comment by harshini-gadige** [comment]
Please keep tracking and post here once Apache Beam is Python 3 ready.

**Comment by lucyktan** [comment]
What is the approximate month/date that this will be ready? My team wants to know for planning purposes. Thanks.

**Comment by katsiapis** [comment]
TFMA 0.13 has support for Python 3.5.

Other version of Python (like 3.6 and 3.7) will follow in future releases (after Beam officially supports them).

Should we close this?

**Comment by ianhellstrom** [comment]
There might still be an issue with Python 3.5 though: #46

**Comment by arghyaganguly** [comment]
Closing this as [tfma](https://pypi.org/project/tensorflow-model-analysis/) supports 3.6,3.7,3.8 now.
