### ISSUE TITLE
Documentation for Slicer.SingleSliceSpec

### ISSUE THREAD

**Issue by pavanky** [tensorflow/model-analysis#82]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow Model Analysis)**: No
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: N/A
-   **TensorFlow Model Analysis installed from (source or binary)**: N/A
-   **TensorFlow Model Analysis version (use command below)**: N/A
-   **Python version**: N/A
-   **Jupyter Notebook version**: N/A
-   **Exact command to reproduce**: N/A

You can obtain the TensorFlow Model Analysis version with

`python -c "import tensorflow_model_analysis as tfma; print(tfma.version.VERSION)"`

### Describe the problem

Documentation for SingleSliceSpec is missing. The [link](https://www.tensorflow.org/tfx/tutorials/model_analysis/tfma_basic#run_tfma_and_render_metrics) from the tutorials goes to the following [page
](https://www.tensorflow.org/tfx/model_analysis/api_docs/python/tfma/SingleSliceSpec
) and 404s

If documentation is available in any other format I'd love to look at it.

**Comment by rmothukuru** [comment]
@pavanky,
In [Github TFMA Release.md](https://github.com/tensorflow/model-analysis/blob/master/RELEASE.md#bug-fixes-and-other-changes-2) it is specified that 

> Deprecated external use of tfma.slicer.SingleSliceSpec (tfma.SlicingSpec should be used instead).

So, please use [tfma.SlicingSpec](https://www.tensorflow.org/tfx/model_analysis/api_docs/python/tfma/SlicingSpec) instead. Thanks!

**Comment by pavanky** [comment]
@rmothukuru thanks! can the tutorial page be updated to the more proper usage?

**Comment by rmothukuru** [comment]
Closing this issue as it has been resolved. Thanks!

**Comment by MMjaberansari** [comment]
Oky thanks for news
