### ISSUE TITLE
Module tensorflow_model_analysis, semver range 0.24.3 is not registered as a widget module

### ISSUE THREAD

**Issue by casassg** [tensorflow/model-analysis#96]
Seems TFMA NPM module was not released for 0.24.3 (https://www.npmjs.com/package/tensorflow_model_analysis latest version is 0.24.2), which breaks UI. Console log:
```
manager.js:305 Uncaught (in promise) Error: Module tensorflow_model_analysis, semver range 0.24.3 is not registered as a widget module
```

**Comment by dhruvesh09** [comment]
TFMA npm module for 0.24.3 is available.

Can you please give a try and let us if there are any issues,
